modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/HorsingAround/issues"
license="MIT"

[[mods]]
modId="horsingaround"
version="${file.jarVersion}"
displayName="Horsing Around"
displayURL="https://www.curseforge.com/minecraft/mc-mods/horsing-around"
authors="Mrbysco, ShyNieke"
description='''
Insert horse pun: neigh
'''
[[dependencies.horsingaround]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.horsingaround]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.117-beta,)"
ordering="NONE"
side="BOTH"