modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/HorsingAround/issues"
license="MIT"

[[mods]]
modId="horsingaround"
version="${file.jarVersion}"
displayName="Horsing Around"
displayURL="https://www.curseforge.com/minecraft/mc-mods/horsing-around"
authors="Mrbysco, ShyNieke"
description='''
Insert horse pun: neigh
'''
[[dependencies.horsingaround]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.horsingaround]]
modId="neoforge"
type="required"
versionRange="[21.0.143,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="horsingaround.mixins.json"